name: ride_booking_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter
  shared_preferences: ^2.2.2
  firebase_core: ^3.12.1
  firebase_auth: ^5.5.1
  cloud_firestore: ^5.6.5
  firebase_messaging: ^15.2.4
  url_launcher: ^6.1.10
  google_fonts: ^6.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  flutter_launcher_icons: ^0.14.3

# Flutter Launcher Icons Configuration
flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/ico.png"
  # For adaptive icons (Android 8.0+):
  # adaptive_icon_foreground: "assets/ico.png"
  # adaptive_icon_background: "#FFFFFF"

flutter:
  uses-material-design: true
  
  assets:
    - assets/ico.png